[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
build_flags = -std=gnu++17 -Wall -D DEBUG_MONITOR=1
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17 -Wall -I include
test_build_src = yes
build_src_filter = +<modules/> +<logic/>
