; LWS-1608 BMS reader - ESP32 / Arduino / NimBLE
; Source: https://github.com/swallowlikeyoshi/bexel-v2-bluetooth-protocol

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = h2zero/NimBLE-Arduino@^1.4.2
monitor_speed = 115200
